language: python
dist: xenial
python:
  - 3.7.1
before_install:
  - pip install poetry~=0.12.0
install:
  - poetry install -E async
# command to run tests
script:
  - poetry run pylint ./gql --output-format=parseable
  - poetry run pytest
