language: python
dist: xenial
python:
  - 3.7.1
before_install:
  - pip install poetry~=0.12.0 coveralls
install:
  - poetry install -E async
# command to run tests
script:
  - make lint
  - make test
after_success: coveralls
